# Generated by Django 4.1 on 2022-08-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img1',
            field=models.ImageField(default='abin', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
